export enum EntityNames {
  User = "user",
  UserOtp = "user_otp",
  UserBankAccount = "user_bank_account",
  Tour = "tour",
  TourPlan = "tour_plan",
  TourPassengers = "tour_passengers",
  Blog = "blog",
  BlogComment = "blog_comment",
  Basket = "basket",
  Reserve = "reserve",
  Payment = "payment",
  Category = "category",
  Discount = "discount",
}
